language: node_js
node_js:
 - "node"

cache: npm

script: VUE_APP_API_CLIENT=$VUE_APP_API_CLIENT VUE_APP_SU_API_BASE_URL=$VUE_APP_SU_API_BASE_URL npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GH_TOKEN
 local_dir: dist
 on:
   branch: develop
